#!/bin/bash
# vim: set ft=sh

set -e

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

# run tests
(
    set -e

    source /docker-lib.sh
    start_docker

    docker load -i verdaccio/image
    docker tag "$(cat verdaccio/image-id)" "$(cat verdaccio/repository):$(cat verdaccio/tag)"

    docker images

    cp -r $PWD/sample-node $GOPATH/src/github.com/idahobean/npm-resource
    cd $GOPATH/src/github.com/idahobean/npm-resource

    COMPOSE_HTTP_TIMEOUT=300 docker-compose -f scripts/docker-compose.yml up -d
    go install github.com/idahobean/npm-resource/vendor/github.com/onsi/ginkgo/ginkgo

    CGO_ENABLED=1 ginkgo -race -r -p "$@"

    COMPOSE_HTTP_TIMEOUT=300 docker-compose -f scripts/docker-compose.yml down
    docker volume rm $(docker volume ls -q)
)

# build binaries
(
    set -e

    cd $GOPATH/src/github.com/idahobean/npm-resource

    export GOPATH=${PWD}/vendor:$GOPATH
    export PATH=${PWD}/vendor/bin:$PATH

    go build -o $BUILD_DIR/built-out ./out/cmd/out
    go build -o $BUILD_DIR/built-check ./check/cmd/check
    go build -o $BUILD_DIR/built-in ./in/cmd/in
)

(
    set -e

    cd $GOPATH/src/github.com/idahobean/npm-resource

    cp Dockerfile $BUILD_DIR
)
